spring:
    application:
        name: ddd-infrastructure

    kafka:
        bootstrap-servers: localhost:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            acks: all
            retries: 3
        consumer:
            group-id: train-booking-group
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            auto-offset-reset: earliest
            enable-auto-commit: false
            properties:
                spring.json.trusted.packages: "org.ddd.ddddomain.model.event"

    datasource:
        url: jdbc:postgresql://localhost:5432/train_booking_db
        username: postgres
        password: h123456aA@
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
